# Generated by Django 6.0.7 on 2026-07-12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticFeedVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        default="staged",
                        max_length=16,
                    ),
                ),
                ("source_url", models.URLField()),
                ("content_sha256", models.CharField(db_index=True, max_length=64)),
                ("archive_object_key", models.CharField(blank=True, max_length=512)),
                ("manifest", models.JSONField(default=dict)),
                ("record_counts", models.JSONField(default=dict)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransitFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("static_source_url", models.URLField()),
                ("realtime_source_url", models.URLField(blank=True)),
                (
                    "agency_timezone",
                    models.CharField(default="Asia/Kuala_Lumpur", max_length=64),
                ),
                ("realtime_priority", models.PositiveSmallIntegerField(default=0)),
                ("is_realtime_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("slug",)},
        ),
        migrations.CreateModel(
            name="GtfsTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.CharField(max_length=160)),
                ("route_id", models.CharField(max_length=160)),
                ("service_id", models.CharField(max_length=160)),
                ("headsign", models.CharField(blank=True, max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=160)),
                ("direction_id", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("block_id", models.CharField(blank=True, max_length=160)),
                ("shape_id", models.CharField(blank=True, max_length=160)),
                ("wheelchair_accessible", models.PositiveSmallIntegerField(default=0)),
                ("bikes_allowed", models.PositiveSmallIntegerField(default=0)),
                (
                    "feed_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GtfsStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.CharField(max_length=160)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_type", models.PositiveSmallIntegerField(default=0)),
                ("parent_station_id", models.CharField(blank=True, max_length=160)),
                ("platform_code", models.CharField(blank=True, max_length=80)),
                ("wheelchair_boarding", models.PositiveSmallIntegerField(default=0)),
                (
                    "feed_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GtfsService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=160)),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "feed_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GtfsRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=160)),
                ("agency_id", models.CharField(blank=True, max_length=160)),
                ("short_name", models.CharField(blank=True, max_length=160)),
                ("long_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("route_type", models.PositiveSmallIntegerField()),
                ("route_color", models.CharField(blank=True, max_length=6)),
                ("text_color", models.CharField(blank=True, max_length=6)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "feed_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GtfsAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_id", models.CharField(max_length=160)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("timezone", models.CharField(max_length=64)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("phone", models.CharField(blank=True, max_length=80)),
                (
                    "feed_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticImportIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("error", "Error")],
                        max_length=8,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("source_file", models.CharField(max_length=100)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("detail", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_issues",
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staticfeedversion",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="transit.transitfeed",
            ),
        ),
        migrations.CreateModel(
            name="GtfsServiceException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                ("exception_type", models.PositiveSmallIntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="transit.gtfsservice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "service_date"),
                        name="unique_service_exception_date",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="GtfsStopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.CharField(max_length=160)),
                ("stop_sequence", models.PositiveIntegerField()),
                ("arrival_time", models.CharField(blank=True, max_length=8)),
                ("departure_time", models.CharField(blank=True, max_length=8)),
                ("arrival_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("departure_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("stop_headsign", models.CharField(blank=True, max_length=255)),
                ("pickup_type", models.PositiveSmallIntegerField(default=0)),
                ("drop_off_type", models.PositiveSmallIntegerField(default=0)),
                ("timepoint", models.PositiveSmallIntegerField(default=1)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_times",
                        to="transit.gtfstrip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trip", "stop_sequence"],
                        name="transit_gtf_trip_id_3e7c56_idx",
                    ),
                    models.Index(fields=["stop_id"], name="transit_gtf_stop_id_747551_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "stop_sequence"),
                        name="unique_stop_sequence_per_trip",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gtfstrip",
            index=models.Index(
                fields=["feed_version", "route_id"],
                name="transit_gtf_feed_ve_18eac4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfstrip",
            index=models.Index(
                fields=["feed_version", "service_id"],
                name="transit_gtf_feed_ve_51cf66_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfstrip",
            constraint=models.UniqueConstraint(
                fields=("feed_version", "trip_id"),
                name="unique_trip_per_static_version",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsstop",
            index=models.Index(
                fields=["feed_version", "latitude", "longitude"],
                name="transit_gtf_feed_ve_9d053f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsstop",
            index=models.Index(
                fields=["feed_version", "name"],
                name="transit_gtf_feed_ve_72fa21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsstop",
            constraint=models.UniqueConstraint(
                fields=("feed_version", "stop_id"),
                name="unique_stop_per_static_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsservice",
            constraint=models.UniqueConstraint(
                fields=("feed_version", "service_id"),
                name="unique_service_per_static_version",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsroute",
            index=models.Index(
                fields=["feed_version", "short_name"],
                name="transit_gtf_feed_ve_c9dabd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gtfsroute",
            index=models.Index(
                fields=["feed_version", "long_name"],
                name="transit_gtf_feed_ve_457615_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsroute",
            constraint=models.UniqueConstraint(
                fields=("feed_version", "route_id"),
                name="unique_route_per_static_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="gtfsagency",
            constraint=models.UniqueConstraint(
                fields=("feed_version", "agency_id"),
                name="unique_agency_per_static_version",
            ),
        ),
        migrations.AddIndex(
            model_name="staticimportissue",
            index=models.Index(
                fields=["version", "severity"],
                name="transit_sta_version_a6a4b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staticimportissue",
            index=models.Index(
                fields=["version", "source_file"],
                name="transit_sta_version_32c95c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staticfeedversion",
            index=models.Index(
                fields=["feed", "status"],
                name="transit_sta_feed_id_967656_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staticfeedversion",
            index=models.Index(
                fields=["feed", "started_at"],
                name="transit_sta_feed_id_5479c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="staticfeedversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("feed",),
                name="one_active_static_version_per_feed",
            ),
        ),
    ]
