# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("transit", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="UpstreamFetchAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("static", "Static GTFS"),
                            ("realtime", "GTFS Realtime"),
                        ],
                        max_length=16,
                    ),
                ),
                ("succeeded", models.BooleanField()),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("detail", models.CharField(blank=True, max_length=240)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_attempts",
                        to="transit.transitfeed",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feed", "kind", "completed_at"],
                        name="transit_ups_feed_id_22295a_idx",
                    ),
                    models.Index(
                        fields=["kind", "succeeded", "completed_at"],
                        name="transit_ups_kind_fb8af5_idx",
                    ),
                ]
            },
        ),
    ]
