# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("transit", "0002_upstreamfetchattempt")]

    operations = [
        migrations.CreateModel(
            name="VehicleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.CharField(max_length=160)),
                ("trip_id", models.CharField(blank=True, max_length=160)),
                ("route_id", models.CharField(blank=True, max_length=160)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "bearing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "speed_metres_per_second",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("position_reported_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                (
                    "validation_state",
                    models.CharField(
                        choices=[
                            ("validated", "Validated"),
                            ("orphan_reference", "Orphan reference"),
                            ("out_of_coverage", "Out of coverage"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_snapshots",
                        to="transit.transitfeed",
                    ),
                ),
                (
                    "feed_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_snapshots",
                        to="transit.staticfeedversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feed", "validation_state", "fetched_at"],
                        name="transit_veh_feed_id_48b7f9_idx",
                    ),
                    models.Index(
                        fields=["feed_version", "trip_id"],
                        name="transit_veh_feed_ve_379e6c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed", "vehicle_id"),
                        name="latest_snapshot_per_feed_vehicle",
                    )
                ],
            },
        ),
    ]
